#!/bin/bash
##  Title:          viuScript
##  Author:         Matt Williams [https://github.com/mattcoding4days]
##
##  Description:    A simple script that tries to make the file transfer
##                  and log in process at bit faster, and easier
##  Version:        1.0
##===========================================================================

##  Constants
SERVER="csci.viu.ca"
IPSERVER="142.25.101.2"

##  takes input from -i and -l command
function login {
    clear
    if [[ $1 && $2 ]]; then
        printf "Logging into VIU server via ip..\n\n"
        ssh -l $1 $IPSERVER
    else
       printf  "Logging into VIU server..\n\n"
       ssh -l $OPTARG $SERVER
   fi
}

##  using scp file tranfer protocol
function fileTransfer {
    clear
    printf "Transferring your files..\n\n"
    scp $1 $2@$SERVER:$3
}

##  Simple help menu
function displayHelp {
    clear
    printf  "Usage: viuScript [OPTION]..\n"
    printf  "\tviuScript is meant to mitigate the login and file transfer process\n"
    printf  "\tAll this information can be found on Dave Wessels Technotes page.\n"
    printf  "\thttp://csci.viu.ca/~wesselsd/technotes.html\n"
    printf  "\t-i <yourUserName>      use ip address to login\n"
    printf  "\t-l <yourUserName>      Login using standard method\n"
    printf  "\t-h                     Display this menu\n"
    printf  "\t-t <file> <yourloginId> /path/to/where/you/want\n"
    printf  "\t[e.g] viuScript -t lab2.cpp johnQpublic csci161/lab2.cpp\n\n"
}

# usage function
function noArrgs {
    echo "script usage: $(basename $0)
    [-l <yourloginId>]
    [-i <yourloginId>]
    [-t <file> <yourloginId> <file>]
    [-h Displays a detailed help menu]" >&2
    exit 1
}

# if no param's are given, execute this
if [ -z "$1" ]
then
    noArrgs
fi

# start the main loop
while getopts 'l:i:t:h' OPTION; do
    case "$OPTION" in
        l)
            lvalue="$OPTARG"
            login $OPTARG
            ;;
        t)
            tvalue1="$1" # will hold -t, so we don't use
            tvalue2="$2"
            tvalue3="$3"
            tvalue4="$4"
            fileTransfer $2 $3 $4
            ;;
        i)
            ivalue1="$1" # will hold -i but we use for the if statement in login
            ivalue2="$2"
            login $1 $2
            ;;
        h)
            displayHelp
            ;;
        ?)
            noArrgs
            ;;
        esac
done
shift "$(($OPTIND -1))"
