#!/bin/bash
##  Title:          viuscript
##  Author:         Matt Williams [https://github.com/mattcoding4days] 
## 
##  Description:    A simple script that tries to make the file transfer
##                  and log in process at bit faster, and easier
##  VERSION         1.5
##===========================================================================

##  Constants
SERVER="csci.viu.ca"

##  takes input -l command
function login {
  local id="$1"
  clear

  printf  "Logging "$id" into "$SERVER"..\n\n"
  ssh -l "$id" "$SERVER"
  local sshRet=$?
  if [[ ! "$sshRet" ]]; then
    printf "ssh failure\n"
  fi
}

## transfer files from local machine to server
function transferToServer {
  filename="$1" 
  id="$2" 
  dest="$3"
  clear
  printf "Transferring "$filename" to "$dest" for "$id" on "$SERVER"\n\n"
  scp "$filename" "$id@$SERVER:$dest"
  scpRet=$?
  if [[ ! "$scpRet" ]]; then
    printf "scp failure\n"
  fi
}

# Transfer files to local machine from server
function transferToLocal {
  id="$1"
  filename="$2"
  dest="$3"

  clear
  printf "Transferring "$filename" to "$dest" on local machine\n\n"
  scp "$id@$SERVER:$filename" "$dest"
  scpRet=$?
  if [[ ! "$scpRet" ]]; then
    printf "scp failure\n"
  fi
}

##  Simple help menu
function displayHelp {
  clear
  printf  "Usage: viuScript [OPTION]..\n"
  printf  "\tviuScript is meant to mitigate the login and file transfer process\n"
  printf  "\tAll this information can be found on Dave Wessels Technotes page.\n"
  printf  "\thttp://csci.viu.ca/~wesselsd/technotes.html\n\n"
  printf  "\t-t sends files from your machine to the server\n"
  printf  "\t-m sends files from the server to your machine\n"
  printf  "\t-l <yourUserName>      Login using standard method\n"
  printf  "\t-t <file> <yourloginId>\n"
  printf  "\t-m <yourloginId> <file> <destination>\n"
  printf  "\t-h Display this menu\n\n"
  printf  "\t[e.g] viuScript -t lab2.cpp johnQpublic\n"
  printf  "\t[e.g] viuScript -m johnQpublic lab2.cpp /home/foo/blah\n\n"
}

# usage function
function noArrgs {
  echo "script usage: $(basename $0)
  [-l <yourloginId>]
  [-t <file> <yourloginId> ]
  [-m <yourloginId> <file> ]
  [-h Displays a detailed help menu]" >&2
  exit 1
}

# if no param's are given, execute this
if [ -z "$1" ]
then
  noArrgs
fi

# start the main loop
while getopts 'l:t:m:h' OPTION; do
  case "$OPTION" in
    l)
      id=$OPTARG
      login "$id"
      ;;
    t)
      filename="$2"
      id="$3"
      destination="$3"
      transferToServer "$filename" "$id" "$destination"
      ;;
    m)
      id="$2"
      filename="$3"
      destination="$4"
      transferToLocal "$id" "$filename" "$destination"
      ;;
    h)
      displayHelp
      ;;
    ?)
      noArrgs
      ;;
  esac
done
shift $(("$OPTIND" -1))
